### ISSUE TITLE
Tests for the plots

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctaplot#110]
Currently only importing stuff is tested.

**Comment by vuillaut** [comment]
?
I don't think that's true... ?
See for example [ctaplot/ana/tests/test_ana.py](https://github.com/cta-observatory/ctaplot/blob/master/ctaplot/ana/tests/test_ana.py)

**Comment by vuillaut** [comment]
Ha I know what misled you, the historical `/tests/test_import.py`
That should probably be removed I think.

**Comment by MaxNoe** [comment]
Ah, sorry,  yes indeed
