### ISSUE TITLE
Tests do not actually run on two different python versions

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctaplot#112]
Although you define python as 3.7 and 3.8 in travis.yml, anaconda will always use 3.7.

We need to make sure, conda installs the correct python version or we don't use conda on travis.

**Comment by vuillaut** [comment]
Ha, thanks for the input, I didn't know that.

**Comment by MaxNoe** [comment]
I don't think this was solved. At least locally, overriding the specified python version did not work for me:

```
$ conda env create -n foo -f environment.yml python=3.6
# lots of output
$ conda activate foo
$ python --version
Python 3.7.7
```

**Comment by MaxNoe** [comment]
Mmh, okay, but here on travis it seemed to work. Maybe it's because you don't specify a python version in environment.yaml
