### ISSUE TITLE
Properly display bins and uncertainties

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctaplot#113]
Most quantities displayed here are actully binned and have uncertainties.

Most plots here just use points connected with lines

**Comment by vuillaut** [comment]
I am sorry, could you be a bit more specific please?

**Comment by MaxNoe** [comment]
Effective area, sensitivity, angular resolution are all defined in energy bins, either vs. true or estimated energy.

Currently, the plots only show bin centers as dots connected with lines.

More appropriate would be showing the bins as horizontal lines, maybe with uncertainties as errobars:

![bins_vs_points](https://user-images.githubusercontent.com/5488440/81074002-b5179580-8ee8-11ea-9e64-0f5f11444329.png)

Also compare the official plots on the cta homepage:

![img](https://www.cta-observatory.org/wp-content/uploads/2019/04/CTA-Performance-prod3b-v2-South-20deg-DifferentialSensitivity.png)

**Comment by vuillaut** [comment]
> Effective area, sensitivity, angular resolution are all defined in energy bins, either vs. true or estimated energy.
> 
> Currently, the plots only show bin centers as dots connected with lines.
> 
> More appropriate would be showing the bins as horizontal lines, maybe with uncertainties as errobars:
> 
> ![bins_vs_points](https://user-images.githubusercontent.com/5488440/81074002-b5179580-8ee8-11ea-9e64-0f5f11444329.png)
> 
> Also compare the official plots on the cta homepage:
> 
> ![img](https://camo.githubusercontent.com/3493deec9d843a2c9f5e19aee5cb65f647d6df06/68747470733a2f2f7777772e6374612d6f627365727661746f72792e6f72672f77702d636f6e74656e742f75706c6f6164732f323031392f30342f4354412d506572666f726d616e63652d70726f6433622d76322d536f7574682d32306465672d446966666572656e7469616c53656e73697469766974792e706e67)

Ho the official CTA IRFs plots, yes you are right!
To be improved.
