### ISSUE TITLE
Bias correction will not solve "aberration bias" for ring wobble (or diffuse) MC

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/ctaplot#190]
So far in the MC we store the nominal focal length. This is used for transformations from camera frame to telescope frame and back. Hence from the reconstructed event directions (x,y), which are affected by aberration (e.g. in LST, light on the camera is shifted outwards w.r.t. the camera center by ~4.66% of the distance to the center, see https://www.mpi-hd.mpg.de/hfm/CTA/MC/Prod3/Config/PSF/flen.pdf), get transformed into (alt, az) assuming perfect optics and introduce a bias (of the same amount) in reco_alt, reco_az. 

For point-like gamma MC with the gamma direction being the same for all events (like LST's old "wobble MC" with source at x=0.4 deg, y=0) the average bias correction in ctaplot will solve the issue:

https://github.com/cta-observatory/ctaplot/blob/8ca1fbf20f1305bfaf1be89945c089f8c920b820/ctaplot/ana/ana.py#L740

This is however not the case for diffuse gamma MC, or for LST's new ring wobble MC. In those cases the average bias will be 0 just due to symmetry, but there is a direction, dependent bias that does not get corrected and will result in an artificially worse angular resolution.

Solution: we have to correct the reco_alt, az using the effective focal length (see https://github.com/cta-observatory/ctapipe/pull/1910) which corrects for the average effect of aberration.  For already existing MC with no effective focal length stored, we have to introduce this manually somehow.

**Comment by vuillaut** [comment]
I am not sure yet to understand what can be done at ctaplot level then.
This is very different for a systematic bias that is independent of how directions have been reconstructed.

As you suggest, I suppose the DL2 quantities have to be patched with this correction before computing the angular reconstruction.

**Comment by moralejo** [comment]
Yes, it is indeed a problem "upstream" of ctaplot. 

Proper fixing requires new MC files which contain effective focal length (rather than nominal), then everything would work fine straightaway.

In order to be able to work with current MC files we could introduce a patch in r0_to_dl1 stage - but this would require re-running the whole MC analysis, while the issue can be fixed really at the last (plotting) stage, because it does not affect anything else (both data and MC are using nominal focal length so RFs should work fine). 

Actually, if we fix it for MC in r0_to_dl1 we would also have to re-generate all real data DL1 with the right conversion (or patch all existing files). Not worth the effort, I think.

**Comment by vuillaut** [comment]
Hi @moralejo 
I have had a look at this issue.
If I understand correctly, the bias is dependent on the position of the source in the camera (both angular and on the distance to the cam center).
See for examlpe the dependence to the angle alpha computed from the X-axis to the event position in the camera:

![Capture d’écran 2022-06-07 à 14 40 52](https://user-images.githubusercontent.com/4263646/172385456-5d847e2d-7781-4621-b101-a1a29589d286.png)



I don't see a simple way to fix such a bias other than modeling it and applying a correction.

If so, the correction should be done outside of ctaplot in my opinion, following something like:
```
dl2_events = read_table(file, path=dl2_params_key)
appy_bias_correction(dl2_events)
ctaplot.plot_theta2(dl2_events)
```

Alternatively, there could be something like:
``` 
ctaplot.plot_theta2(dl2_events, bias_correction=bias_correction)
``` 
with the correction an array of bias values, but that makes little difference in my opinion.

Or am I missing something?

**Comment by vuillaut** [comment]
For reference, this as been solved using lstchain
```
from lstchain.reco.utils import reco_source_position_sky
```
with the effective focal length.

See https://github.com/cta-observatory/cta-lstchain/pull/1001
