### ISSUE TITLE
plot_migration_matrix unable to change bins

### ISSUE THREAD

**Issue by BastienLacave** [cta-observatory/ctaplot#203]
Unable to change bins of the hist2d in plot_migration_matrix because of (line 1143):
if 'bins_x' not in hist2d_args:
        hist2d_args['bins'] = 50
Here 'bins_x' should be 'bins', because otherwise we get a keyword error when hist2d_args are passed to
h = ax.hist2d(x, y, **hist2d_args)
due to the presence of 'bins_x' keyword.

**Comment by vuillaut** [comment]
Hi @BastienLacave 
Thank you for reporting this!
PR #204 should fix that.
Cheers
